/* GENERATED by build-form-map.js — do not edit by hand.
   Source of truth: ../questionnaire/questionnaire.js */
'use strict';
module.exports = {
  "REF": "CQ-FEP-01",
  "DOC": [
    {
      "id": "clientName",
      "ar": "اسم العميل / الشركة",
      "en": "Client / Company Name"
    },
    {
      "id": "formDate",
      "ar": "تاريخ الاستبيان",
      "en": "Questionnaire Date"
    },
    {
      "id": "projectTitle",
      "ar": "اسم المشروع",
      "en": "Project Title"
    },
    {
      "id": "preparedBy",
      "ar": "إعداد",
      "en": "Prepared By"
    },
    {
      "id": "sector",
      "ar": "القطاع / النشاط",
      "en": "Sector / Industry"
    },
    {
      "id": "version",
      "ar": "رقم الإصدار",
      "en": "Document Version"
    },
    {
      "id": "location",
      "ar": "الموقع المقترح",
      "en": "Proposed Location"
    },
    {
      "id": "contactName",
      "ar": "مسؤول التواصل",
      "en": "Main Contact Person"
    },
    {
      "id": "contactEmail",
      "ar": "البريد الإلكتروني",
      "en": "Contact Email"
    },
    {
      "id": "contactPhone",
      "ar": "رقم الهاتف",
      "en": "Contact Phone"
    }
  ],
  "FX": [
    {
      "id": "fxRate",
      "ar": "سعر صرف الدولار مقابل الجنيه",
      "en": "USD / EGP Exchange Rate"
    },
    {
      "id": "fxSource",
      "ar": "مصدر السعر",
      "en": "Rate Source"
    },
    {
      "id": "fxType",
      "ar": "نوع السعر",
      "en": "Rate Type"
    },
    {
      "id": "fxDate",
      "ar": "تاريخ السعر",
      "en": "Rate Date"
    }
  ],
  "GROUPS": [
    {
      "id": "A",
      "ar": "نطاق الاستثمار والأعمال",
      "en": "Investment & Business Scope",
      "q": [
        {
          "id": "A1",
          "ar": "ما هي الميزانية الاستثمارية التقريبية المتاحة للمشروع؟",
          "en": "What is the approximate investment budget available for the project?"
        },
        {
          "id": "A2",
          "ar": "ما هو النطاق الجغرافي المستهدف للمشروع؟",
          "en": "What is the intended market scope of the project?"
        },
        {
          "id": "A3",
          "ar": "ما هو الهدف الرئيسي من إنشاء المصنع في مصر؟",
          "en": "What is the main objective of establishing the factory in Egypt?"
        },
        {
          "id": "A4",
          "ar": "ما هو الإطار الزمني المستهدف لبدء الإنتاج؟",
          "en": "What is the target timeline for starting commercial production?"
        }
      ]
    },
    {
      "id": "B",
      "ar": "العمليات الحالية ونقل الأصول",
      "en": "Existing Operations & Asset Transfer",
      "q": [
        {
          "id": "B1",
          "ar": "هل سيتم نقل أي ماكينات أو خطوط إنتاج من مصنع السودان إلى مصر؟",
          "en": "Will any machinery or production lines be transferred from the Sudan factory to Egypt?"
        },
        {
          "id": "B2",
          "ar": "إذا كانت الإجابة نعم، ما هي المعدات أو خطوط الإنتاج التي سيتم نقلها؟",
          "en": "If yes, which machinery or production lines will be transferred?"
        },
        {
          "id": "B3",
          "ar": "هل سيكون المشروع الجديد Greenfield بالكامل؟",
          "en": "Will the new project be a fully Greenfield investment?"
        },
        {
          "id": "B4",
          "ar": "ما هي الطاقة الإنتاجية الحالية لمصنع السودان؟",
          "en": "What is the current production capacity of the Sudan factory?"
        },
        {
          "id": "B5",
          "ar": "ما هي الطاقة الإنتاجية المستهدفة للمصنع الجديد في مصر؟",
          "en": "What is the target production capacity of the new factory in Egypt?"
        }
      ]
    },
    {
      "id": "C",
      "ar": "المنتجات ومحفظة المنتجات",
      "en": "Products & Product Portfolio",
      "q": [
        {
          "id": "C1",
          "ar": "ما هي فئات المنتجات التي ترغبون في البدء بها؟",
          "en": "Which product categories would you like to start with?"
        },
        {
          "id": "C2",
          "ar": "ما هي المنتجات التي يتميز بها المصنع الحالي؟",
          "en": "Which products are you currently strongest in?"
        },
        {
          "id": "C3",
          "ar": "هل تخططون لإنتاج نفس المنتجات الحالية في مصر؟",
          "en": "Do you plan to manufacture the same existing products in Egypt?"
        },
        {
          "id": "C4",
          "ar": "هل تخططون لإضافة منتجات جديدة للسوق المصري؟",
          "en": "Do you plan to introduce new products specifically for the Egyptian market?"
        }
      ]
    },
    {
      "id": "D",
      "ar": "السوق والتموضع لدى العملاء",
      "en": "Market & Customer Positioning",
      "q": [
        {
          "id": "D1",
          "ar": "من هو العميل المستهدف في السوق المصري؟",
          "en": "Who is your target customer segment in the Egyptian market?"
        },
        {
          "id": "D2",
          "ar": "ما هو مستوى السعر المستهدف للمنتجات؟",
          "en": "What is the intended price positioning of the products?"
        },
        {
          "id": "D3",
          "ar": "من هم المنافسون الرئيسيون الذين تستهدفون منافستهم؟",
          "en": "Who are the main competitors you intend to compete with?"
        },
        {
          "id": "D4",
          "ar": "ما هي الحصة السوقية المستهدفة؟",
          "en": "What market share are you targeting?"
        }
      ]
    },
    {
      "id": "E",
      "ar": "هيكل الاستثمار والتمويل",
      "en": "Investment Structure & Financing",
      "q": [
        {
          "id": "E1",
          "ar": "هل سيكون الاستثمار بتمويل ذاتي بالكامل؟",
          "en": "Will the investment be fully self-funded?"
        },
        {
          "id": "E2",
          "ar": "هل سيتم الاعتماد على تسهيلات ائتمانية أو قروض بنكية؟",
          "en": "Will bank loans or credit facilities be used to finance the project?"
        },
        {
          "id": "E3",
          "ar": "ما قيمة التمويل الخارجي المتوقع؟",
          "en": "What is the expected external financing amount?"
        },
        {
          "id": "E4",
          "ar": "ما هي الميزانية التقديرية للمعدات والآلات؟",
          "en": "What is the estimated budget for machinery and equipment?"
        },
        {
          "id": "E5",
          "ar": "ما هي الميزانية التقديرية للمباني والتجهيزات؟",
          "en": "What is the estimated budget for buildings and infrastructure?"
        },
        {
          "id": "E6",
          "ar": "ما هي الميزانية التقديرية لرأس المال العامل؟",
          "en": "What is the estimated working capital requirement?"
        }
      ]
    },
    {
      "id": "F",
      "ar": "المعرفة الفنية والتركيبات",
      "en": "Technical Know-how & Formulations",
      "q": [
        {
          "id": "F1",
          "ar": "هل تمتلكون تركيبات كيميائية جاهزة للمنتجات؟",
          "en": "Do you already have established chemical formulations for your products?"
        },
        {
          "id": "F2",
          "ar": "هل سيتم تطبيق نفس التركيبات المستخدمة في السودان في مصر؟",
          "en": "Will the same formulations currently used in Sudan be applied in Egypt?"
        },
        {
          "id": "F3",
          "ar": "هل تحتاجون إلى تطوير تركيبات جديدة للسوق المصري؟",
          "en": "Do you require new formulations specifically developed for the Egyptian market?"
        },
        {
          "id": "F4",
          "ar": "هل تم اختبار توافق التركيبات مع المواد الخام المحلية؟",
          "en": "Have the formulations been tested for compatibility with locally available raw materials?"
        },
        {
          "id": "F5",
          "ar": "هل توجد معرفة فنية أو حقوق ملكية فكرية يجب نقلها للمصنع الجديد؟",
          "en": "Is there any technical know-how or intellectual property that needs to be transferred to the new factory?"
        }
      ]
    },
    {
      "id": "G",
      "ar": "المواد الخام وسلسلة التوريد",
      "en": "Raw Materials & Supply Chain",
      "q": [
        {
          "id": "G1",
          "ar": "هل تخططون للاعتماد على مواد خام محلية أم مستوردة؟",
          "en": "Do you plan to use locally sourced or imported raw materials?"
        },
        {
          "id": "G1b",
          "ar": "إذا كانت مختلطة، ما نسبة المواد المحلية؟",
          "en": "If mixed, what percentage is locally sourced?"
        },
        {
          "id": "G2",
          "ar": "ما هي المواد الخام الرئيسية المطلوبة؟",
          "en": "What are the main raw materials required for production?"
        },
        {
          "id": "G3",
          "ar": "هل لديكم موردون حاليون سيتم نقل التعامل معهم إلى مصر؟",
          "en": "Do you have existing suppliers that you intend to continue working with in Egypt?"
        },
        {
          "id": "G4",
          "ar": "هل توجد مواد خام حساسة من ناحية التوفر أو الأسعار؟",
          "en": "Are there any critical raw materials with significant availability or price risks?"
        }
      ]
    },
    {
      "id": "H",
      "ar": "متطلبات المصنع والموقع",
      "en": "Factory & Location Requirements",
      "q": [
        {
          "id": "H1",
          "ar": "هل تم تحديد موقع المصنع في مصر؟",
          "en": "Has a factory location in Egypt already been identified?"
        },
        {
          "id": "H2",
          "ar": "إذا كان الموقع محدداً، فما هي المنطقة؟",
          "en": "If yes, where is the proposed location?"
        },
        {
          "id": "H3",
          "ar": "ما هي المساحة المطلوبة تقريباً للمصنع؟",
          "en": "What is the approximate required factory area?"
        },
        {
          "id": "H4",
          "ar": "هل توجد متطلبات خاصة للمرافق؟",
          "en": "Are there any specific utility requirements?"
        }
      ]
    },
    {
      "id": "I",
      "ar": "الإنتاج والجودة",
      "en": "Production & Quality",
      "q": [
        {
          "id": "I1",
          "ar": "هل سيتم تشغيل المصنع بنفس معايير الجودة الحالية؟",
          "en": "Will the new factory operate under the same quality standards as the existing factory?"
        },
        {
          "id": "I2",
          "ar": "هل توجد شهادات جودة مطلوبة؟",
          "en": "Are there specific quality certifications required?"
        },
        {
          "id": "I3",
          "ar": "ما هي الطاقة التشغيلية المستهدفة في المرحلة الأولى؟",
          "en": "What is the targeted operating capacity during Phase 1?"
        },
        {
          "id": "I4",
          "ar": "هل هناك خطة للتوسع المستقبلي؟",
          "en": "Is there a plan for future production expansion?"
        },
        {
          "id": "I4b",
          "ar": "إذا نعم، ما هي الطاقة المتوقعة بعد التوسع؟",
          "en": "If yes, what is the expected capacity after expansion?"
        }
      ]
    },
    {
      "id": "J",
      "ar": "المبيعات والتوزيع والتصدير",
      "en": "Sales, Distribution & Export",
      "q": [
        {
          "id": "J1",
          "ar": "كيف سيتم توزيع المنتجات في السوق المصري؟",
          "en": "How will the products be distributed in the Egyptian market?"
        },
        {
          "id": "J2",
          "ar": "هل توجد شبكة توزيع قائمة بالفعل؟",
          "en": "Do you already have an established distribution network?"
        },
        {
          "id": "J3",
          "ar": "هل التصدير جزء أساسي من استراتيجية المشروع؟",
          "en": "Is export a key part of the project's strategy?"
        },
        {
          "id": "J3b",
          "ar": "إذا نعم، ما النسبة المستهدفة من المبيعات؟",
          "en": "If yes, what target share of sales?"
        },
        {
          "id": "J4",
          "ar": "ما هي الدول المستهدفة للتصدير؟",
          "en": "Which countries are targeted for export?"
        }
      ]
    },
    {
      "id": "K",
      "ar": "تنفيذ المشروع",
      "en": "Project Implementation",
      "q": [
        {
          "id": "K1",
          "ar": "متى ترغبون في بدء أعمال التصميم والتأسيس؟",
          "en": "When would you like to start the design and project implementation activities?"
        },
        {
          "id": "K2",
          "ar": "متى يجب أن يبدأ الإنتاج التجاري؟",
          "en": "By when should commercial production start?"
        },
        {
          "id": "K3",
          "ar": "هل توجد أي مواعيد نهائية مرتبطة بالسوق أو التمويل؟",
          "en": "Are there any market, financing, or business deadlines that must be met?"
        },
        {
          "id": "K4",
          "ar": "من سيكون صاحب القرار الرئيسي في المشروع؟",
          "en": "Who will be the main decision-maker for the project?"
        }
      ]
    },
    {
      "id": "L",
      "ar": "معلومات إضافية",
      "en": "Additional Information",
      "q": [
        {
          "id": "L1",
          "ar": "هل توجد أي متطلبات أو افتراضات أخرى يجب أخذها في الاعتبار؟",
          "en": "Are there any additional requirements, assumptions, or constraints that should be considered?"
        },
        {
          "id": "L2",
          "ar": "هل يمكن مشاركة أي دراسات أو بيانات سابقة للمشروع؟",
          "en": "Can you provide any existing studies, business plans, production data, or technical documents?"
        }
      ]
    }
  ],
  "FIN": [
    {
      "id": "F1",
      "n": "1",
      "ar": "الآلات والمعدات",
      "en": "Machinery & Equipment"
    },
    {
      "id": "F2",
      "n": "2",
      "ar": "الأعمال المدنية والمباني",
      "en": "Civil Works / Factory Buildings"
    },
    {
      "id": "F3",
      "n": "3",
      "ar": "المرافق والبنية التحتية",
      "en": "Utilities & Infrastructure"
    },
    {
      "id": "F4",
      "n": "4",
      "ar": "رأس المال العامل",
      "en": "Working Capital"
    },
    {
      "id": "F5",
      "n": "5",
      "ar": "استثمارات أخرى",
      "en": "Other Investment"
    }
  ],
  "MEMO": [
    {
      "id": "M1",
      "n": "M1",
      "ar": "إجمالي الميزانية الاستثمارية (حسب العميل)",
      "en": "Total Investment Budget (as stated by client)"
    },
    {
      "id": "M2",
      "n": "M2",
      "ar": "التمويل الخارجي (قروض / تسهيلات)",
      "en": "External Financing (loans / credit facilities)"
    }
  ],
  "DOCS": [
    {
      "id": "D1",
      "n": "1",
      "ar": "خطة العمل",
      "en": "Business plan"
    },
    {
      "id": "D2",
      "n": "2",
      "ar": "بيانات الإنتاج التاريخية",
      "en": "Historical production data"
    },
    {
      "id": "D3",
      "n": "3",
      "ar": "قائمة الآلات والمعدات",
      "en": "Machinery & equipment list"
    },
    {
      "id": "D4",
      "n": "4",
      "ar": "تركيبات المنتجات",
      "en": "Product formulations"
    },
    {
      "id": "D5",
      "n": "5",
      "ar": "المستندات والرسومات الفنية",
      "en": "Technical documents & drawings"
    },
    {
      "id": "D6",
      "n": "6",
      "ar": "دراسات السوق",
      "en": "Market studies"
    }
  ],
  "OPTIONS": {
    "__yn": {
      "yes": {
        "ar": "نعم",
        "en": "Yes"
      },
      "no": {
        "ar": "لا",
        "en": "No"
      }
    },
    "fxType": {
      "official": {
        "ar": "رسمي",
        "en": "Official"
      },
      "bank": {
        "ar": "بنكي",
        "en": "Bank"
      },
      "market": {
        "ar": "سوق",
        "en": "Market"
      }
    },
    "A2": {
      "local": {
        "ar": "السوق المحلي",
        "en": "Local market"
      },
      "export": {
        "ar": "التصدير",
        "en": "Export"
      },
      "both": {
        "ar": "كلاهما",
        "en": "Both"
      }
    },
    "B1": {
      "yes": {
        "ar": "نعم",
        "en": "Yes"
      },
      "no": {
        "ar": "لا",
        "en": "No"
      }
    },
    "B3": {
      "yes": {
        "ar": "نعم",
        "en": "Yes"
      },
      "no": {
        "ar": "لا",
        "en": "No"
      },
      "partial": {
        "ar": "جزئيًا",
        "en": "Partial"
      }
    },
    "C1": {
      "powder": {
        "ar": "منظفات بودرة",
        "en": "Powder detergents"
      },
      "liquid": {
        "ar": "منظفات سائلة",
        "en": "Liquid detergents"
      },
      "dish": {
        "ar": "منظفات أطباق",
        "en": "Dishwashing"
      },
      "surface": {
        "ar": "منظفات أسطح",
        "en": "Surface cleaners"
      },
      "personal": {
        "ar": "العناية الشخصية",
        "en": "Personal care"
      },
      "other": {
        "ar": "أخرى",
        "en": "Other"
      }
    },
    "C3": {
      "yes": {
        "ar": "نعم",
        "en": "Yes"
      },
      "no": {
        "ar": "لا",
        "en": "No"
      }
    },
    "C4": {
      "yes": {
        "ar": "نعم",
        "en": "Yes"
      },
      "no": {
        "ar": "لا",
        "en": "No"
      }
    },
    "D1": {
      "economy": {
        "ar": "اقتصادي",
        "en": "Economy"
      },
      "mass": {
        "ar": "السوق العام",
        "en": "Mass market"
      },
      "middle": {
        "ar": "الشريحة المتوسطة",
        "en": "Middle"
      },
      "premium": {
        "ar": "المتميز",
        "en": "Premium"
      },
      "mixed": {
        "ar": "مختلط",
        "en": "Mixed"
      }
    },
    "E1": {
      "yes": {
        "ar": "نعم",
        "en": "Yes"
      },
      "no": {
        "ar": "لا",
        "en": "No"
      }
    },
    "E2": {
      "yes": {
        "ar": "نعم",
        "en": "Yes"
      },
      "no": {
        "ar": "لا",
        "en": "No"
      }
    },
    "F1": {
      "yes": {
        "ar": "نعم",
        "en": "Yes"
      },
      "no": {
        "ar": "لا",
        "en": "No"
      }
    },
    "F2": {
      "yes": {
        "ar": "نعم",
        "en": "Yes"
      },
      "no": {
        "ar": "لا",
        "en": "No"
      }
    },
    "F3": {
      "yes": {
        "ar": "نعم",
        "en": "Yes"
      },
      "no": {
        "ar": "لا",
        "en": "No"
      }
    },
    "F4": {
      "yes": {
        "ar": "نعم",
        "en": "Yes"
      },
      "no": {
        "ar": "لا",
        "en": "No"
      }
    },
    "G1": {
      "local": {
        "ar": "محلية",
        "en": "Local"
      },
      "imported": {
        "ar": "مستوردة",
        "en": "Imported"
      },
      "mixed": {
        "ar": "مختلطة",
        "en": "Mixed"
      }
    },
    "H1": {
      "yes": {
        "ar": "نعم",
        "en": "Yes"
      },
      "no": {
        "ar": "لا",
        "en": "No"
      }
    },
    "H4": {
      "power": {
        "ar": "كهرباء",
        "en": "Electricity"
      },
      "water": {
        "ar": "مياه",
        "en": "Water"
      },
      "gas": {
        "ar": "غاز",
        "en": "Gas"
      },
      "steam": {
        "ar": "بخار",
        "en": "Steam"
      },
      "wastewater": {
        "ar": "صرف صناعي",
        "en": "Wastewater"
      },
      "other": {
        "ar": "أخرى",
        "en": "Other"
      }
    },
    "I1": {
      "yes": {
        "ar": "نعم",
        "en": "Yes"
      },
      "no": {
        "ar": "لا",
        "en": "No"
      }
    },
    "I2": {
      "iso9001": {
        "ar": "ISO 9001",
        "en": "ISO 9001"
      },
      "iso14001": {
        "ar": "ISO 14001",
        "en": "ISO 14001"
      },
      "gmp": {
        "ar": "GMP",
        "en": "GMP"
      },
      "halal": {
        "ar": "حلال",
        "en": "Halal"
      },
      "other": {
        "ar": "أخرى",
        "en": "Other"
      }
    },
    "I4": {
      "yes": {
        "ar": "نعم",
        "en": "Yes"
      },
      "no": {
        "ar": "لا",
        "en": "No"
      }
    },
    "J1": {
      "distributors": {
        "ar": "موزعون",
        "en": "Distributors"
      },
      "direct": {
        "ar": "بيع مباشر",
        "en": "Direct sales"
      },
      "retail": {
        "ar": "تجزئة تقليدية",
        "en": "Traditional retail"
      },
      "modern": {
        "ar": "التجارة الحديثة",
        "en": "Modern trade"
      },
      "ecom": {
        "ar": "التجارة الإلكترونية",
        "en": "E-commerce"
      }
    },
    "J2": {
      "yes": {
        "ar": "نعم",
        "en": "Yes"
      },
      "no": {
        "ar": "لا",
        "en": "No"
      }
    },
    "J3": {
      "yes": {
        "ar": "نعم",
        "en": "Yes"
      },
      "no": {
        "ar": "لا",
        "en": "No"
      }
    }
  }
};
